# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [ generate-gh-pages ]

    # schedule:
    # - cron: "*/10 * * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: event-${{ github.event_name }}  # So UT won't be interrupted by cronjobs
  cancel-in-progress: true # Avoid batch pending when one job hangs

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      TOKENIZERS_PARALLELISM: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: My Host
        run: |
          echo -e "free -h:\n`free -h`"
          echo -e "df -h:\n`df -h`"
          echo "pwd: `pwd`"
          echo "nproc: `nproc`"
          echo "curl -s ifconfig.me/all:\n`curl -s ifconfig.me/all`"

      - name: Export vars to env
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
          # cache: 'pip'

      # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
      - name: Python Runtime Cache
        id: python-runtime-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Huggingface Model Cache
        id: huggingface-model-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface/hub/models*
          key: ${{ runner.os }}-huggingface

      #      - name: LLaMA 2 model
      #        run: |
      #          mkdir -p ~/.cache/huggingface/hub/
      #          ls -alh ~/.cache/huggingface/hub/
      #          curl -L -o ~/.cache/huggingface/hub/models_llama-2-7b-chat.Q6_K.gguf -z ~/.cache/huggingface/hub/models_llama-2-7b-chat.Q6_K.gguf https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf

      - name: Install Python Dependencies
        run: pip install --upgrade -r requirements.txt

      - name: Download Page Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: 'github-pages'
          path: 'output'
          workflow_conclusion: success

      - name: Extract Page Artifact
        run: |
          tar -xf output/artifact.tar -C output
          rm output/artifact.tar
          rm output/image/.gitignore
          echo -e "df -h:\n`df -h`"

      - name: Unit Test
        run: make test
        if: ${{ github.event_name == 'push' }}

      - name: Generate Daily Page
        run: make gh_daily_page
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SYSLOG_ADDRESS: ${{ secrets.SYSLOG_ADDRESS }}
        if: ${{ endswith(github.run_id, '3') || endswith(github.run_id, '6') || endswith(github.run_id, '9') }}

      - name: Generate Home Page
        run: make gh_home_page
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SYSLOG_ADDRESS: ${{ secrets.SYSLOG_ADDRESS }}

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'output'
          retention-days: 7

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        if: ${{ success() }}
